name: Build AltF10 Library

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    permissions:
      contents: read
      packages: write

    steps:
    - name: Check out Git repository
      uses: actions/checkout@v4

    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 22

    - name: Install Dependencies
      run: npm install
      
    - name: Build Electron App (Unsigned)
      run: npm run electron:build
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
